Sylius\Component\Product\Model\ProductTranslation:
    properties:
        name:
            - NotBlank:
                message: sylius.product.name.not_blank
                groups: [app_product]
            - Length:
                min: 10
                minMessage: sylius.product.name.min_length
                max: 255
                maxMessage: sylius.product.name.max_length
                groups: [app_product]
        slug:
            - NotBlank:
                  message: sylius.product.slug.not_blank
                  groups: [app_product]
            - Length:
                  max: 255
                  maxMessage: sylius.product.slug.max_length
                  groups: [app_product]
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [locale, slug]
            errorPath: slug
            message: sylius.product.slug.unique
            groups: [app_product]
