app_shop_partial_product_index_by_on_hand:
    path: /partial/products/by-on-hand
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: '@SyliusShop/Product/_horizontalList.html.twig'
            repository:
                method: findAllByOnHand
                arguments: [4]
            criteria: false
        paginate: false
        limit: 100
